### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [DavidLining/3D_PathPlanner#1]
Hello, under what license is this project released under ? Thank-you.

**Comment by DavidLining** [comment]
You can use for free

**Comment by DavidLining** [comment]
open source

**Comment by zhengkexin97** [comment]
Could you please provide relevant literature of A* algorithm? thank you!

**Comment by DavidLining** [comment]
>

**Comment by DavidLining** [comment]
I have no reference paper, it's a common algorithm, you can find it everywhere.
